Update build-openwrt.yml

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -113,9 +113,9 @@ jobs:
       if: env.SKIP_TARGET == '0'
       run: scripts/cisteps/build-openwrt/07-download_openwrt.sh
 
-    - name: Apply customizations
-      if: env.SKIP_TARGET == '0'
-      run: scripts/cisteps/build-openwrt/08-customize.sh
+    #- name: Apply customizations
+    #  if: env.SKIP_TARGET == '0'
+    #  run: scripts/cisteps/build-openwrt/08-customize.sh
 
     # Allow intermediate customization
     #- name: '[Debug/Menuconfig] Wait for SSH connection (timeout 30min)'
@@ -151,13 +151,13 @@ jobs:
       run: df -h
 
     # failure checking
-    - name: '[Failure/Debug] Wait for SSH connection (timeout 30min)'
-      if: |
-        env.SKIP_TARGET == '0' && !cancelled()
-        && (job.status == 'failure' || (env.OPT_DEBUG == '1' && env.TEST != '1'))
-      env:
-        TMATE_DOCKER_CONTAINER: ${{env.BUILDER_CONTAINER_ID}}
-      uses: tete1030/safe-debugger-action@dev
+    #- name: '[Failure/Debug] Wait for SSH connection (timeout 30min)'
+    #  if: |
+    #    env.SKIP_TARGET == '0' && !cancelled()
+    #    && (job.status == 'failure' || (env.OPT_DEBUG == '1' && env.TEST != '1'))
+    #  env:
+    #    TMATE_DOCKER_CONTAINER: ${{env.BUILDER_CONTAINER_ID}}
+    #  uses: tete1030/safe-debugger-action@dev
 
     - name: Upload builder
       if: |
@@ -194,8 +194,8 @@ jobs:
         path: ${{env.HOST_BIN_DIR}}
 
     # failure checking
-    - name: '[Failure/Debug] wait for SSH connection (timeout 30min. You are safe to cancel the job now.)'
-      if: |
-        env.SKIP_TARGET == '0' && !cancelled()
-        && (job.status == 'failure' || (env.OPT_DEBUG == '1' && env.TEST != '1'))
-      uses: tete1030/safe-debugger-action@dev
+    #- name: '[Failure/Debug] wait for SSH connection (timeout 30min. You are safe to cancel the job now.)'
+    #  if: |
+    #    env.SKIP_TARGET == '0' && !cancelled()
+    #    && (job.status == 'failure' || (env.OPT_DEBUG == '1' && env.TEST != '1'))
+    #  uses: tete1030/safe-debugger-action@dev
